
[Train] Epoch: 1/5:   0%|          | 0/656 [00:00<?, ?batch/s]






[Train] Epoch: 1/5:  96%|█████████▌| 630/656 [00:14<00:00, 56.42batch/s, accuracy=0.943, loss=0.155]
[Train] Epoch: 1/5: 100%|██████████| 656/656 [00:14<00:00, 44.63batch/s, accuracy=0.981, loss=0.155]





[Train] Epoch: 2/5:  98%|█████████▊| 642/656 [00:11<00:00, 56.52batch/s, accuracy=0.985, loss=4.68e-5]
[Train] Epoch: 2/5: 100%|██████████| 656/656 [00:11<00:00, 55.93batch/s, accuracy=1, loss=4.71e-5]




[Train] Epoch: 3/5:  83%|████████▎ | 546/656 [00:09<00:01, 55.57batch/s, accuracy=0.834, loss=1.32e-5]
[Train] Epoch: 3/5: 100%|██████████| 656/656 [00:11<00:00, 55.86batch/s, accuracy=1, loss=1.49e-5]





[Train] Epoch: 4/5:  86%|████████▌ | 564/656 [00:10<00:01, 56.30batch/s, accuracy=0.86, loss=6.35e-6]
[Train] Epoch: 4/5: 100%|██████████| 656/656 [00:11<00:00, 56.06batch/s, accuracy=1, loss=6.98e-6]





[Train] Epoch: 5/5:  87%|████████▋ | 570/656 [00:10<00:01, 55.03batch/s, accuracy=0.872, loss=3.13e-6]
best model Info --> epoch: 5 | accuracy: 0.999999
[Train] Epoch: 5/5: 100%|██████████| 656/656 [00:11<00:00, 55.33batch/s, accuracy=1, loss=3.39e-6]
Traceback (most recent call last):
  File "C:/Users/Choo/PycharmProjects/Applications and Open Challenges in Federated Learning/Week1/Run.py", line 101, in <module>
    model = torch.load(f'best_model/[ep{best_epoch}_{best_accuracy:0.6f}].pth').to(device)
  File "C:\Users\Choo\anaconda3\envs\gwangggi\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Choo\anaconda3\envs\gwangggi\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Choo\anaconda3\envs\gwangggi\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'best_model/[ep5_0.999999].pth'